# Prompts for AI analysis
from .thumbnail_prompt import (
    THUMBNAIL_ANALYSIS_PROMPT,
    THUMBNAIL_SYSTEM_INSTRUCTION,
    THUMBNAIL_USER_PROMPT,
)
from .title_description_prompt import (
    TITLE_DESCRIPTION_ANALYSIS_PROMPT,
    TITLE_DESC_SYSTEM_INSTRUCTION,
    TITLE_DESC_USER_PROMPT,
)

__all__ = [
    'THUMBNAIL_ANALYSIS_PROMPT',
    'THUMBNAIL_SYSTEM_INSTRUCTION',
    'THUMBNAIL_USER_PROMPT',
    'TITLE_DESCRIPTION_ANALYSIS_PROMPT',
    'TITLE_DESC_SYSTEM_INSTRUCTION',
    'TITLE_DESC_USER_PROMPT',
]
